// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"database/sql"
	"time"
)

type Profile struct {
	ID       int64  `json:"id"`
	RealName string `json:"real_name"`
	// 1:男, 2:女, 0:未知
	Gender    sql.NullInt32  `json:"gender"`
	Quote     sql.NullString `json:"quote"`
	Address   sql.NullString `json:"address"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`
	UserID    int64          `json:"user_id"`
}

type User struct {
	ID             int64          `json:"id"`
	Username       string         `json:"username"`
	HashedPassword string         `json:"hashed_password"`
	Nickname       string         `json:"nickname"`
	Avatar         sql.NullString `json:"avatar"`
	Status         sql.NullBool   `json:"status"`
	IsSuper        sql.NullBool   `json:"is_super"`
	CreatedAt      time.Time      `json:"created_at"`
	UpdatedAt      time.Time      `json:"updated_at"`
}
