// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.16.0

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProfile(ctx context.Context, arg CreateProfileParams) (Profile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteUser(ctx context.Context, arg DeleteUserParams) (User, error)
	QueryUsers(ctx context.Context, arg QueryUsersParams) ([]QueryUsersRow, error)
	RetrieveProfile(ctx context.Context, userID int64) (RetrieveProfileRow, error)
	RetrieveUserByID(ctx context.Context, id int64) (RetrieveUserByIDRow, error)
	RetrieveUserByUsername(ctx context.Context, username string) (RetrieveUserByUsernameRow, error)
	UpdateAdmin(ctx context.Context, arg UpdateAdminParams) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateProfile(ctx context.Context, arg UpdateProfileParams) (Profile, error)
}

var _ Querier = (*Queries)(nil)
